version: "3.9"

services:

  auth-service:
    build: ./auth-service
    ports:
      - "4005:4005"
    networks:
      - pm-net

  patient-service:
    build: ./patient-service
    ports:
      - "4000:4000"
    networks:
      - pm-net

  billing-service:
    build: ./billing-service
    ports:
      - "4001:4001"
    networks:
      - pm-net

  analytics-service:
    build: ./analytics-service
    ports:
      - "4002:4002"
    networks:
      - pm-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "4004:4004"
    networks:
      - pm-net

networks:
  pm-net:
    driver: bridge
