server:
  port: 4004

spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: http://auth-service.patient-management.local:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: patient-service
          uri: http://patient-service.patient-management.local:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=2
            - JwtValidation

        - id: appointment-service
          uri: http://appointment-service.patient-management.local:4006
          predicates:
            - Path=/api/appointments/**
          filters:
            - StripPrefix=2
            - JwtValidation

        - id: api-docs-patient
          uri: http://patient-service.patient-management.local:4000
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs

        - id: api-docs-auth
          uri: http://auth-service.patient-management.local:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        - id: api-docs-appointment
          uri: http://appointment-service.patient-management.local:4006
          predicates:
            - Path=/api-docs/appointments
          filters:
            - RewritePath=/api-docs/appointments,/v3/api-docs